/* ---------------------------
   1) CREATE DATABASE y USE
   --------------------------- */
IF DB_ID('Monster_University') IS NULL
BEGIN
    CREATE DATABASE Monster_University;
END
GO

USE Monster_University;
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* ---------------------------
   2) TABLAS
   --------------------------- */

-- aeasi_asign
CREATE TABLE dbo.aeasi_asign (
  AEASI_ID nvarchar(10) NOT NULL,
  AEPRER_IDREQUISITO int NULL,
  AEASI_CODIGO nvarchar(10) NOT NULL,
  AEASI_NOMBRE nvarchar(50) NOT NULL,
  AEASI_CREDITOS int NOT NULL,
  DESCRIPCIONASIGNATURA nvarchar(200) NULL,
  CONSTRAINT PK_aeasi_asign PRIMARY KEY (AEASI_ID)
);
GO

-- aecar_carrer
CREATE TABLE dbo.aecar_carrer (
  IDCARRERA nvarchar(10) NOT NULL,
  NOMBRECARRERA nvarchar(50) NOT NULL,
  CODIGOCARRERA nvarchar(10) NOT NULL,
  MAX_CREDITOSCARRERA decimal(12,0) NOT NULL,
  MIN_CREDITOSCARRERA decimal(12,0) NOT NULL,
  CONSTRAINT PK_aecar_carrer PRIMARY KEY (IDCARRERA)
);
GO

-- aedet_detmatri
CREATE TABLE dbo.aedet_detmatri (
  AEDET_ID_DETLL nvarchar(10) NOT NULL,
  AEMAT_ID_MATRICULA nvarchar(10) NOT NULL,
  AEGRU_CODIGO nvarchar(20) NOT NULL,
  AEDET_NOTAFINAL decimal(10,2) NULL,
  AEDET_ESTADOASIGNATURA nvarchar(32) NOT NULL,
  AEDET_FECHAINSCRIPCION date NOT NULL,
  AEDET_FECHARETIRO date NULL,
  CONSTRAINT PK_aedet_detmatri PRIMARY KEY (AEDET_ID_DETLL)
);
GO

-- aeest_estud
CREATE TABLE dbo.aeest_estud (
  AEEST_ID nvarchar(10) NOT NULL,
  XEPER_ID int NOT NULL,
  IDCARRERA nvarchar(10) NOT NULL,
  AEEST_CODIGO_EST nvarchar(9) NOT NULL,
  AEEST_FECHA_ING_EST date NOT NULL,
  AEEST_PROMEDIO decimal(3,2) NOT NULL,
  AEEST_ESTADO_PAGO bit NOT NULL,
  AEEST_ESTUDI nvarchar(16) NULL,
  CONSTRAINT PK_aeest_estud PRIMARY KEY (AEEST_ID)
);
GO

-- aegru_grupo
CREATE TABLE dbo.aegru_grupo (
  AEGRU_CODIGO nvarchar(20) NOT NULL,
  AEASI_ID nvarchar(10) NOT NULL,
  IDPERIODO nvarchar(10) NOT NULL,
  PEDOC_ID nvarchar(10) NOT NULL,
  AEGRU_AULA nvarchar(20) NOT NULL,
  AEGRU_CUPO_MAX int NOT NULL,
  AEGRU_CUPO_ACTUAL int NOT NULL,
  HORARIOGRUPO nvarchar(max) NULL,
  CONSTRAINT PK_aegru_grupo PRIMARY KEY (AEGRU_CODIGO)
);
GO

-- aemat_matri
CREATE TABLE dbo.aemat_matri (
  AEMAT_ID_MATRICULA nvarchar(10) NOT NULL,
  AEEST_ID nvarchar(10) NOT NULL,
  IDPERIODO nvarchar(10) NOT NULL,
  AEMAT_FECHA_MATRI date NOT NULL,
  AEMAT_ESTADO_MATRICULA nvarchar(20) NOT NULL,
  AEMAT_TOTAL_CREDIT_MATRI int NOT NULL,
  AEMAT_TOTAL_ASIGNA_MATRI int NOT NULL,
  IDCARRERA nvarchar(10) NOT NULL,
  CONSTRAINT PK_aemat_matri PRIMARY KEY (AEMAT_ID_MATRICULA)
);
GO

-- aeper_period
CREATE TABLE dbo.aeper_period (
  IDPERIODO nvarchar(10) NOT NULL,
  NOMBREPERIODO nvarchar(50) NOT NULL,
  FECHA_INICIOPERIODO date NOT NULL,
  FECHA_FINPERIODO date NOT NULL,
  ACTIVOPERIODO bit NOT NULL,
  CONSTRAINT PK_aeper_period PRIMARY KEY (IDPERIODO)
);
GO

-- aeprer_prerre
CREATE TABLE dbo.aeprer_prerre (
  AEPRER_IDREQUISITO int NOT NULL,
  AEPRER_NOMBREREQUISITO nvarchar(64) NOT NULL,
  AEPRER_TIPO_REQUI nvarchar(16) NOT NULL,
  AEPRER_DESCRIPCIONREQUISITO nvarchar(128) NULL,
  CONSTRAINT PK_aeprer_prerre PRIMARY KEY (AEPRER_IDREQUISITO)
);
GO

-- febec_beca
CREATE TABLE dbo.febec_beca (
  FEBEC_CODIGOBECA char(10) NOT NULL,
  FEBEC_NOMBREBECA nvarchar(50) NOT NULL,
  FEBEC_DESCRIPCIONB nvarchar(100) NULL,
  FEBEC_PORCENTAJE int NOT NULL,
  CONSTRAINT PK_febec_beca PRIMARY KEY (FEBEC_CODIGOBECA)
);
GO

-- fecaf_cabfac
CREATE TABLE dbo.fecaf_cabfac (
  FECAF_NUMFAC char(6) NOT NULL,
  FEBEC_CODIGOBECA char(10) NULL,
  AEEST_ID nvarchar(10) NOT NULL,
  FECAF_FECEMI date NOT NULL,
  FECAF_AUTSRI nvarchar(50) NULL,
  FECAF_FEASRI datetime2 NULL,
  FECAF_IVA decimal(10,2) NOT NULL,
  FECAF_DESCUES decimal(10,2) NULL,
  FECAF_TOTPAG decimal(10,2) NOT NULL,
  FECAF_SUBTOT decimal(10,2) NOT NULL,
  FECAF_ESTADO nvarchar(25) NOT NULL,
  IDCARRERA nvarchar(10) NOT NULL,
  CONSTRAINT PK_fecaf_cabfac PRIMARY KEY (FECAF_NUMFAC)
);
GO

-- fecpo_cpag
CREATE TABLE dbo.fecpo_cpag (
  FECPO_CODIGO char(10) NOT NULL,
  FECPO_NOMBRE nvarchar(50) NOT NULL,
  FECPO_DESCRIPCION nvarchar(100) NOT NULL,
  FECPO_VALOR decimal(10,2) NOT NULL,
  CONSTRAINT PK_fecpo_cpag PRIMARY KEY (FECPO_CODIGO)
);
GO

-- fedet_deta
CREATE TABLE dbo.fedet_deta (
  FEDET_CODIGO char(10) NOT NULL,
  FECAF_NUMFAC char(6) NOT NULL,
  FECPO_CODIGO char(10) NOT NULL,
  FEDET_CANTIDAD int NOT NULL,
  FEDET_TOTAL decimal(10,2) NOT NULL,
  CONSTRAINT PK_fedet_deta PRIMARY KEY (FEDET_CODIGO)
);
GO

-- fefpg_fpag
CREATE TABLE dbo.fefpg_fpag (
  FEFPG_CODIGO char(10) NOT NULL,
  FEPAG_CODIGO char(10) NOT NULL,
  FEFPG_NOMBRE nvarchar(50) NOT NULL,
  CONSTRAINT PK_fefpg_fpag PRIMARY KEY (FEFPG_CODIGO)
);
GO

-- fepag_pago
CREATE TABLE dbo.fepag_pago (
  FEPAG_CODIGO char(10) NOT NULL,
  FECAF_NUMFAC char(6) NOT NULL,
  FEPAG_MONTO decimal(10,2) NOT NULL,
  FEPAG_FECHAPAGO date NOT NULL,
  CONSTRAINT PK_fepag_pago PRIMARY KEY (FEPAG_CODIGO)
);
GO

-- pecar_cargo
CREATE TABLE dbo.pecar_cargo (
  PECAR_CODIGO nvarchar(10) NOT NULL,
  PECAR_NOMBRE nvarchar(20) NOT NULL,
  PECAR_DESCRI nvarchar(20) NULL,
  CONSTRAINT PK_pecar_cargo PRIMARY KEY (PECAR_CODIGO)
);
GO

-- pedep_depa
CREATE TABLE dbo.pedep_depa (
  PEDEP_CODIGO nvarchar(10) NOT NULL,
  PEDEP_NOMBRE nvarchar(50) NOT NULL,
  PEDEP_AREA nvarchar(20) NULL,
  CONSTRAINT PK_pedep_depa PRIMARY KEY (PEDEP_CODIGO)
);
GO

-- pedoc_docen
CREATE TABLE dbo.pedoc_docen (
  PEDOC_ID nvarchar(10) NOT NULL,
  XEPER_ID int NOT NULL,
  PEDOC_ESPECIALIDAD nvarchar(32) NULL,
  PEDOC_NIVEL nvarchar(32) NULL,
  PEDOC_ESTADO nvarchar(16) NULL,
  PEDOC_FCH_INICIO date NULL,
  CONSTRAINT PK_pedoc_docen PRIMARY KEY (PEDOC_ID)
);
GO

-- peemp_emple
CREATE TABLE dbo.peemp_emple (
  PEEMP_CODIGO nvarchar(10) NOT NULL,
  XEPER_ID int NOT NULL,
  PEDEP_CODIGO nvarchar(10) NOT NULL,
  PECAR_CODIGO nvarchar(10) NOT NULL,
  PEEMP_CARGAS decimal(2,0) NOT NULL,
  PEEMP_FECHAINGRESO date NOT NULL,
  PEEMP_JORNADALABORAL nvarchar(64) NOT NULL,
  PEEMP_ESTADOEMPLEADO nvarchar(32) NOT NULL,
  CONSTRAINT PK_peemp_emple PRIMARY KEY (PEEMP_CODIGO)
);
GO

-- peesc_estciv
CREATE TABLE dbo.peesc_estciv (
  PEESC_CODIGO char(1) NOT NULL,
  PEESC_DESCRI nvarchar(20) NOT NULL,
  CONSTRAINT PK_peesc_estciv PRIMARY KEY (PEESC_CODIGO)
);
GO

-- pesex_sexo
CREATE TABLE dbo.pesex_sexo (
  PESEX_CODIGO nvarchar(10) NOT NULL,
  PESEX_DESCRI nvarchar(50) NOT NULL,
  CONSTRAINT PK_pesex_sexo PRIMARY KEY (PESEX_CODIGO)
);
GO

-- xeacu_usr_acade
CREATE TABLE dbo.xeacu_usr_acade (
  XEUSU_ID_USUARIO int NOT NULL,
  TIPO nvarchar(20) NOT NULL,
  ID_ACADEMICO nvarchar(20) NOT NULL,
  FECCRE datetime2 NOT NULL DEFAULT (SYSUTCDATETIME()),
  FECMOD datetime2 NULL,
  CONSTRAINT PK_xeacu_usr_acade PRIMARY KEY (XEUSU_ID_USUARIO)
);
GO

-- xeest_estad
CREATE TABLE dbo.xeest_estad (
  XEEST_CODIGO char(1) NOT NULL,
  XEEST_DESCRI nvarchar(50) NOT NULL,
  CONSTRAINT PK_xeest_estad PRIMARY KEY (XEEST_CODIGO)
);
GO

-- xeopc_opcio
CREATE TABLE dbo.xeopc_opcio (
  XEOPC_CODIGO char(3) NOT NULL,
  XESIS_CODIGO char(1) NOT NULL,
  XEOPC_DESCRI nvarchar(100) NOT NULL,
  CONSTRAINT PK_xeopc_opcio PRIMARY KEY (XEOPC_CODIGO)
);
GO

-- xeoxp_opcpe
CREATE TABLE dbo.xeoxp_opcpe (
  XEOPC_CODIGO char(3) NOT NULL,
  XEPER_CODIGO char(8) NOT NULL,
  XEOXP_FECASI date NOT NULL,
  XEOXP_FECRET date NULL,
  CONSTRAINT PK_xeoxp_opcpe PRIMARY KEY (XEOPC_CODIGO, XEPER_CODIGO)
);
GO

-- xeper_perfi
CREATE TABLE dbo.xeper_perfi (
  XEPER_CODIGO char(8) NOT NULL,
  XEPER_DESCRI nvarchar(100) NOT NULL,
  XEPER_OBSER nvarchar(max) NULL,
  CONSTRAINT PK_xeper_perfi PRIMARY KEY (XEPER_CODIGO)
);
GO

-- xeper_persona
CREATE TABLE dbo.xeper_persona (
  XEPER_ID int NOT NULL IDENTITY(1,1),
  PEESC_CODIGO char(1) NOT NULL,
  PESEX_CODIGO nvarchar(10) NOT NULL,
  XEPER_CEDULA nvarchar(10) NULL,
  XEPER_NOMBRES nvarchar(128) NOT NULL,
  XEPER_APELLIDOS nvarchar(128) NOT NULL,
  XEPER_FECHANAC date NOT NULL,
  XEPER_DIRECCION nvarchar(264) NULL,
  XEPER_TELEFONO nvarchar(10) NULL,
  XEPER_EMAIL nvarchar(128) NOT NULL,
  XEPER_FECREGISTRO datetime2 NOT NULL,
  XEPER_TIPO_PERSONA char(1) NULL,
  CONSTRAINT PK_xeper_persona PRIMARY KEY (XEPER_ID)
);
GO

-- xesec_secuencias
CREATE TABLE dbo.xesec_secuencias (
  TIPO nvarchar(20) NOT NULL,
  ULTIMO_NUMERO int NOT NULL DEFAULT 0,
  CONSTRAINT PK_xesec_secuencias PRIMARY KEY (TIPO)
);
GO

-- xesis_siste
CREATE TABLE dbo.xesis_siste (
  XESIS_CODIGO char(1) NOT NULL,
  XESIS_DESCRI nvarchar(50) NOT NULL,
  CONSTRAINT PK_xesis_siste PRIMARY KEY (XESIS_CODIGO)
);
GO

-- xetrec_tokenrec
CREATE TABLE dbo.xetrec_tokenrec (
  XETREC_ID int NOT NULL IDENTITY(1,1),
  XEUSU_ID_USUARIO int NOT NULL,
  XETREC_TOKEN nvarchar(255) NOT NULL,
  XETREC_CREACION datetime2 NULL DEFAULT (SYSUTCDATETIME()),
  XETREC_EXPIRACION datetime2 NOT NULL,
  XETREC_USADO char(1) NULL DEFAULT 'N',
  CONSTRAINT PK_xetrec_tokenrec PRIMARY KEY (XETREC_ID)
);
GO

-- xeusu_usuar
CREATE TABLE dbo.xeusu_usuar (
  XEUSU_ID_USUARIO int NOT NULL IDENTITY(1,1),
  XEPER_ID int NOT NULL,
  XEEST_CODIGO char(1) NOT NULL,
  PEEMP_CODIGO nvarchar(10) NULL,
  XEUSU_USERNAME nvarchar(32) NOT NULL,
  PASSWORDHASH nvarchar(255) NOT NULL,
  EMAIL_USUARIO nvarchar(128) NULL,
  XEUSU_PIEFIR nvarchar(100) NULL,
  XEUSU_FECCRE datetime2 NOT NULL,
  XEUSU_FECMOD datetime2 NULL,
  FOTO_PATH nvarchar(300) NULL,
  PRIMER_INGRESO char(1) NULL DEFAULT 'S',
  CONTRASE�A_TEMPORAL char(1) NULL DEFAULT 'N',
  CONSTRAINT PK_xeusu_usuar PRIMARY KEY (XEUSU_ID_USUARIO)
);
GO

-- xeuxp_usupe
CREATE TABLE dbo.xeuxp_usupe (
  XEUSU_ID_USUARIO int NOT NULL,
  XEPER_CODIGO char(8) NOT NULL,
  XEUXP_FECASI date NOT NULL,
  XEUXP_FECRET date NULL,
  CONSTRAINT PK_xeuxp_usupe PRIMARY KEY (XEUSU_ID_USUARIO, XEPER_CODIGO)
);
GO