
/* ---------------------------
   3) INDICES y CONSTRAINTS (FKs)
   --------------------------- */

-- Indices / Uniques
CREATE UNIQUE INDEX UK_ASIGN_CODIGO ON dbo.aeasi_asign (AEASI_CODIGO);
CREATE INDEX IDX_AEPRER_IDREQUISITO ON dbo.aeasi_asign (AEPRER_IDREQUISITO);

CREATE UNIQUE INDEX UK_CARRERA_CODIGO ON dbo.aecar_carrer (CODIGOCARRERA);

CREATE UNIQUE INDEX UK_ESTUDIANTE_CODIGO ON dbo.aeest_estud (AEEST_CODIGO_EST);
CREATE INDEX IDX_AEEST_XEPER_ID ON dbo.aeest_estud (XEPER_ID);
CREATE INDEX IDX_AEEST_IDCARRERA ON dbo.aeest_estud (IDCARRERA);

CREATE UNIQUE INDEX UK_XEACU_ID_ACADEMICO ON dbo.xeacu_usr_acade (ID_ACADEMICO);
CREATE INDEX IDX_XEACU_TIPO ON dbo.xeacu_usr_acade (TIPO);

CREATE UNIQUE INDEX UK_USUARIO_USERNAME ON dbo.xeusu_usuar (XEUSU_USERNAME);

CREATE UNIQUE INDEX UK_PERSONA_CEDULA ON dbo.xeper_persona (XEPER_CEDULA);

CREATE UNIQUE INDEX UK_XETREC_TOKEN ON dbo.xetrec_tokenrec (XETREC_TOKEN);

-- Foreign Keys
ALTER TABLE dbo.aeasi_asign
  ADD CONSTRAINT FK_ASIGN_PREREQ FOREIGN KEY (AEPRER_IDREQUISITO) REFERENCES dbo.aeprer_prerre (AEPRER_IDREQUISITO);
GO

ALTER TABLE dbo.aedet_detmatri
  ADD CONSTRAINT FK_DETMAT_GRUPO FOREIGN KEY (AEGRU_CODIGO) REFERENCES dbo.aegru_grupo (AEGRU_CODIGO);
GO

ALTER TABLE dbo.aedet_detmatri
  ADD CONSTRAINT FK_DETMAT_MATRI FOREIGN KEY (AEMAT_ID_MATRICULA) REFERENCES dbo.aemat_matri (AEMAT_ID_MATRICULA) ON DELETE CASCADE;
GO

ALTER TABLE dbo.aeest_estud
  ADD CONSTRAINT FK_ESTU_CARRERA FOREIGN KEY (IDCARRERA) REFERENCES dbo.aecar_carrer (IDCARRERA);
GO

ALTER TABLE dbo.aeest_estud
  ADD CONSTRAINT FK_ESTU_PERSONA FOREIGN KEY (XEPER_ID) REFERENCES dbo.xeper_persona (XEPER_ID);
GO

ALTER TABLE dbo.aegru_grupo
  ADD CONSTRAINT FK_GRUPO_ASIGN FOREIGN KEY (AEASI_ID) REFERENCES dbo.aeasi_asign (AEASI_ID);
GO

ALTER TABLE dbo.aegru_grupo
  ADD CONSTRAINT FK_GRUPO_DOCENTE FOREIGN KEY (PEDOC_ID) REFERENCES dbo.pedoc_docen (PEDOC_ID);
GO

ALTER TABLE dbo.aegru_grupo
  ADD CONSTRAINT FK_GRUPO_PERIODO FOREIGN KEY (IDPERIODO) REFERENCES dbo.aeper_period (IDPERIODO);
GO

ALTER TABLE dbo.aemat_matri
  ADD CONSTRAINT FK_MATRI_CARRERA FOREIGN KEY (IDCARRERA) REFERENCES dbo.aecar_carrer (IDCARRERA);
GO

ALTER TABLE dbo.aemat_matri
  ADD CONSTRAINT FK_MATRI_ESTU FOREIGN KEY (AEEST_ID) REFERENCES dbo.aeest_estud (AEEST_ID);
GO

ALTER TABLE dbo.aemat_matri
  ADD CONSTRAINT FK_MATRI_PERIODO FOREIGN KEY (IDPERIODO) REFERENCES dbo.aeper_period (IDPERIODO);
GO

ALTER TABLE dbo.fecaf_cabfac
  ADD CONSTRAINT FK_CABFAC_BECA FOREIGN KEY (FEBEC_CODIGOBECA) REFERENCES dbo.febec_beca (FEBEC_CODIGOBECA);
GO

ALTER TABLE dbo.fecaf_cabfac
  ADD CONSTRAINT FK_CABFAC_CARRERA FOREIGN KEY (IDCARRERA) REFERENCES dbo.aecar_carrer (IDCARRERA);
GO

ALTER TABLE dbo.fecaf_cabfac
  ADD CONSTRAINT FK_CABFAC_ESTU FOREIGN KEY (AEEST_ID) REFERENCES dbo.aeest_estud (AEEST_ID);
GO

ALTER TABLE dbo.fedet_deta
  ADD CONSTRAINT FK_DETA_CABFAC FOREIGN KEY (FECAF_NUMFAC) REFERENCES dbo.fecaf_cabfac (FECAF_NUMFAC) ON DELETE CASCADE;
GO

ALTER TABLE dbo.fedet_deta
  ADD CONSTRAINT FK_DETA_CONCEP FOREIGN KEY (FECPO_CODIGO) REFERENCES dbo.fecpo_cpag (FECPO_CODIGO);
GO

ALTER TABLE dbo.fefpg_fpag
  ADD CONSTRAINT FK_FPAG_PAGO FOREIGN KEY (FEPAG_CODIGO) REFERENCES dbo.fepag_pago (FEPAG_CODIGO);
GO

ALTER TABLE dbo.fepag_pago
  ADD CONSTRAINT FK_PAGO_CABFAC FOREIGN KEY (FECAF_NUMFAC) REFERENCES dbo.fecaf_cabfac (FECAF_NUMFAC);
GO

ALTER TABLE dbo.pedoc_docen
  ADD CONSTRAINT FK_DOCENTE_PERSONA FOREIGN KEY (XEPER_ID) REFERENCES dbo.xeper_persona (XEPER_ID);
GO

ALTER TABLE dbo.peemp_emple
  ADD CONSTRAINT FK_EMPLE_CARGO FOREIGN KEY (PECAR_CODIGO) REFERENCES dbo.pecar_cargo (PECAR_CODIGO);
GO

ALTER TABLE dbo.peemp_emple
  ADD CONSTRAINT FK_EMPLE_DEPA FOREIGN KEY (PEDEP_CODIGO) REFERENCES dbo.pedep_depa (PEDEP_CODIGO);
GO

ALTER TABLE dbo.peemp_emple
  ADD CONSTRAINT FK_EMPLE_PERSONA FOREIGN KEY (XEPER_ID) REFERENCES dbo.xeper_persona (XEPER_ID);
GO

ALTER TABLE dbo.xeacu_usr_acade
  ADD CONSTRAINT FK_XEACU_USR FOREIGN KEY (XEUSU_ID_USUARIO) REFERENCES dbo.xeusu_usuar (XEUSU_ID_USUARIO) ON DELETE CASCADE;
GO

ALTER TABLE dbo.xeopc_opcio
  ADD CONSTRAINT FK_XESIS_OPC FOREIGN KEY (XESIS_CODIGO) REFERENCES dbo.xesis_siste (XESIS_CODIGO);
GO

ALTER TABLE dbo.xeoxp_opcpe
  ADD CONSTRAINT FK_OPCION_OPCPER FOREIGN KEY (XEOPC_CODIGO) REFERENCES dbo.xeopc_opcio (XEOPC_CODIGO);
GO

ALTER TABLE dbo.xeoxp_opcpe
  ADD CONSTRAINT FK_PERFIL_OPCPER FOREIGN KEY (XEPER_CODIGO) REFERENCES dbo.xeper_perfi (XEPER_CODIGO);
GO

ALTER TABLE dbo.xeper_persona
  ADD CONSTRAINT FK_PERSONA_ESTCIV FOREIGN KEY (PEESC_CODIGO) REFERENCES dbo.peesc_estciv (PEESC_CODIGO);
GO

ALTER TABLE dbo.xeper_persona
  ADD CONSTRAINT FK_PERSONA_SEXO FOREIGN KEY (PESEX_CODIGO) REFERENCES dbo.pesex_sexo (PESEX_CODIGO);
GO

ALTER TABLE dbo.xetrec_tokenrec
  ADD CONSTRAINT FK_TOKEN_USUARIO FOREIGN KEY (XEUSU_ID_USUARIO) REFERENCES dbo.xeusu_usuar (XEUSU_ID_USUARIO) ON DELETE CASCADE;
GO

ALTER TABLE dbo.xeusu_usuar
  ADD CONSTRAINT FK_USU_EMPLE FOREIGN KEY (PEEMP_CODIGO) REFERENCES dbo.peemp_emple (PEEMP_CODIGO);
GO

ALTER TABLE dbo.xeusu_usuar
  ADD CONSTRAINT FK_USU_ESTADO FOREIGN KEY (XEEST_CODIGO) REFERENCES dbo.xeest_estad (XEEST_CODIGO);
GO

ALTER TABLE dbo.xeusu_usuar
  ADD CONSTRAINT FK_USU_PERSONA FOREIGN KEY (XEPER_ID) REFERENCES dbo.xeper_persona (XEPER_ID);
GO

ALTER TABLE dbo.xeuxp_usupe
  ADD CONSTRAINT FK_USUPE_PERFIL FOREIGN KEY (XEPER_CODIGO) REFERENCES dbo.xeper_perfi (XEPER_CODIGO);
GO

ALTER TABLE dbo.xeuxp_usupe
  ADD CONSTRAINT FK_USUPE_USUARIO FOREIGN KEY (XEUSU_ID_USUARIO) REFERENCES dbo.xeusu_usuar (XEUSU_ID_USUARIO) ON DELETE CASCADE;
GO